import { createContext, useContext, useEffect, useMemo, useState, type PropsWithChildren } from 'react';
import * as SecureStore from 'expo-secure-store';
import { I18nManager } from 'react-native';

export const languages = [
  { code: 'bn', label: 'Bangla', nativeLabel: 'বাংলা' },
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'id', label: 'Indonesian', nativeLabel: 'Bahasa Indonesia' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'ar', label: 'Arabic', nativeLabel: 'العربية' },
  { code: 'es', label: 'Spanish', nativeLabel: 'Español' },
  { code: 'pt', label: 'Portuguese', nativeLabel: 'Português' },
] as const;

export type LanguageCode = typeof languages[number]['code'];
const LANGUAGE_KEY = 'xyteee.language';
const rtlLanguages = new Set<LanguageCode>(['ar']);

const translations: Record<LanguageCode, Record<string, string>> = {
  en: { messages: 'Messages', contacts: 'Contacts', settings: 'Settings', profile: 'Profile', account: 'ACCOUNT', notification: 'Notification', notifications: 'Notifications', darkMode: 'Dark mode', language: 'Language', editProfile: 'Edit profile', uploadPhoto: 'Upload photo', saveChanges: 'Save changes', signOut: 'Sign out', appearance: 'Appearance', connected: 'Connected', offline: 'Offline', search: 'Search', chooseLanguage: 'Choose language', online: 'Online now', noFriends: 'No friends yet', authWelcome: 'Welcome back', authLoginSubtitle: 'Sign in to continue your conversations.', authCreate: 'Create your account', authRegisterSubtitle: 'Join XYTEEE and start connecting with your people.', authFullName: 'Full name', authUsername: 'Username', authEmail: 'Email address', authPassword: 'Password', authPasswordMinimum: 'Password, at least 8 characters', authConfirmPassword: 'Confirm password', authShowPassword: 'Show password', authHidePassword: 'Hide password', authForgotPassword: 'Forgot password?', authContinue: 'Continue', authCreateAccount: 'Create account', authOr: 'or', authContinueGoogle: 'Continue with Google', authSignupGoogle: 'Sign up with Google', authNoAccount: 'Don’t have an account?', authHaveAccount: 'Already have an account?', authSignup: 'Sign up', authSignin: 'Sign in', authPasswordsMismatch: 'Passwords do not match', authUnableSignin: 'Unable to sign in', authUnableCreate: 'Unable to create account', authRecoveryUnavailable: 'Password recovery is not configured yet.', authGoogleUnavailable: 'Google authentication is ready for configuration but is not enabled yet.', authVoiceOn: 'Voice help on', authVoiceOff: 'Voice help off', authVoiceStart: 'Turn on voice help', authVoiceStop: 'Turn off voice help', authVoiceLoginGuide: 'Welcome to sign in. Enter your email address, then your password. Use Forgot Password if you need recovery help. You may continue with Google, switch language from the top menu, or sign up for a new account.', authVoiceRegisterGuide: 'Welcome to account creation. Enter your full name, choose a username, enter your email address, create a password of at least eight characters, and confirm it. You may sign up with Google, switch language from the top menu, or return to sign in.' },
  bn: { messages: 'বার্তা', contacts: 'যোগাযোগ', settings: 'সেটিংস', profile: 'প্রোফাইল', account: 'অ্যাকাউন্ট', notification: 'নোটিফিকেশন', notifications: 'নোটিফিকেশন', darkMode: 'ডার্ক মোড', language: 'ভাষা', editProfile: 'প্রোফাইল সম্পাদনা', uploadPhoto: 'ছবি আপলোড', saveChanges: 'পরিবর্তন সংরক্ষণ', signOut: 'সাইন আউট', appearance: 'দেখানোর ধরন', connected: 'সংযুক্ত', offline: 'অফলাইন', search: 'খুঁজুন', chooseLanguage: 'ভাষা বেছে নিন', online: 'এখন অনলাইন', noFriends: 'এখনও কোনো বন্ধু নেই', authWelcome: 'আবার স্বাগতম', authLoginSubtitle: 'আপনার কথোপকথন চালিয়ে যেতে সাইন ইন করুন।', authCreate: 'আপনার অ্যাকাউন্ট তৈরি করুন', authRegisterSubtitle: 'XYTEEE-তে যোগ দিন এবং পরিচিতদের সঙ্গে যুক্ত হন।', authFullName: 'পুরো নাম', authUsername: 'ইউজারনেম', authEmail: 'ইমেইল ঠিকানা', authPassword: 'পাসওয়ার্ড', authPasswordMinimum: 'পাসওয়ার্ড, কমপক্ষে ৮ অক্ষর', authConfirmPassword: 'পাসওয়ার্ড নিশ্চিত করুন', authShowPassword: 'পাসওয়ার্ড দেখান', authHidePassword: 'পাসওয়ার্ড লুকান', authForgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?', authContinue: 'চালিয়ে যান', authCreateAccount: 'অ্যাকাউন্ট তৈরি করুন', authOr: 'অথবা', authContinueGoogle: 'Google দিয়ে চালিয়ে যান', authSignupGoogle: 'Google দিয়ে সাইন আপ করুন', authNoAccount: 'অ্যাকাউন্ট নেই?', authHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?', authSignup: 'সাইন আপ', authSignin: 'সাইন ইন', authPasswordsMismatch: 'পাসওয়ার্ড দুটি মিলছে না', authUnableSignin: 'সাইন ইন করা যায়নি', authUnableCreate: 'অ্যাকাউন্ট তৈরি করা যায়নি', authRecoveryUnavailable: 'পাসওয়ার্ড পুনরুদ্ধার এখনো কনফিগার করা হয়নি।', authGoogleUnavailable: 'Google অথেন্টিকেশন কনফিগারেশনের জন্য প্রস্তুত, তবে এখনো চালু নয়।', authVoiceOn: 'ভয়েস সহায়তা চালু', authVoiceOff: 'ভয়েস সহায়তা বন্ধ', authVoiceStart: 'ভয়েস সহায়তা চালু করুন', authVoiceStop: 'ভয়েস সহায়তা বন্ধ করুন', authVoiceLoginGuide: 'সাইন ইন করতে স্বাগতম। আপনার ইমেইল ঠিকানা এবং পাসওয়ার্ড লিখুন। প্রয়োজনে পাসওয়ার্ড ভুলে গেছেন বিকল্পটি ব্যবহার করুন। আপনি Google দিয়ে চালিয়ে যেতে পারেন, উপরের মেনু থেকে ভাষা পরিবর্তন করতে পারেন, অথবা নতুন অ্যাকাউন্ট তৈরি করতে পারেন।', authVoiceRegisterGuide: 'অ্যাকাউন্ট তৈরিতে স্বাগতম। আপনার পুরো নাম লিখুন, একটি ইউজারনেম বেছে নিন, ইমেইল ঠিকানা দিন এবং কমপক্ষে আট অক্ষরের একটি পাসওয়ার্ড তৈরি করে নিশ্চিত করুন। আপনি Google দিয়ে সাইন আপ করতে পারেন, উপরের মেনু থেকে ভাষা পরিবর্তন করতে পারেন, অথবা সাইন ইন-এ ফিরে যেতে পারেন।' },
  id: { messages: 'Pesan', contacts: 'Kontak', settings: 'Pengaturan', profile: 'Profil', account: 'AKUN', notification: 'Notifikasi', notifications: 'Notifikasi', darkMode: 'Mode gelap', language: 'Bahasa', editProfile: 'Edit profil', uploadPhoto: 'Unggah foto', saveChanges: 'Simpan perubahan', signOut: 'Keluar', appearance: 'Tampilan', connected: 'Terhubung', offline: 'Offline', search: 'Cari', chooseLanguage: 'Pilih bahasa', online: 'Sedang online', noFriends: 'Belum ada teman', authWelcome: 'Selamat datang kembali', authLoginSubtitle: 'Masuk untuk melanjutkan percakapan Anda.', authCreate: 'Buat akun Anda', authRegisterSubtitle: 'Bergabunglah dengan XYTEEE dan terhubung dengan orang-orang Anda.', authFullName: 'Nama lengkap', authUsername: 'Nama pengguna', authEmail: 'Alamat email', authPassword: 'Kata sandi', authPasswordMinimum: 'Kata sandi, minimal 8 karakter', authConfirmPassword: 'Konfirmasi kata sandi', authShowPassword: 'Tampilkan kata sandi', authHidePassword: 'Sembunyikan kata sandi', authForgotPassword: 'Lupa kata sandi?', authContinue: 'Lanjutkan', authCreateAccount: 'Buat akun', authOr: 'atau', authContinueGoogle: 'Lanjutkan dengan Google', authSignupGoogle: 'Daftar dengan Google', authNoAccount: 'Belum punya akun?', authHaveAccount: 'Sudah punya akun?', authSignup: 'Daftar', authSignin: 'Masuk', authPasswordsMismatch: 'Kata sandi tidak cocok', authUnableSignin: 'Tidak dapat masuk', authUnableCreate: 'Tidak dapat membuat akun', authRecoveryUnavailable: 'Pemulihan kata sandi belum dikonfigurasi.', authGoogleUnavailable: 'Autentikasi Google siap dikonfigurasi tetapi belum diaktifkan.', authVoiceOn: 'Bantuan suara aktif', authVoiceOff: 'Bantuan suara nonaktif', authVoiceStart: 'Aktifkan bantuan suara', authVoiceStop: 'Nonaktifkan bantuan suara', authVoiceLoginGuide: 'Selamat datang di halaman masuk. Masukkan alamat email lalu kata sandi Anda. Gunakan opsi Lupa Kata Sandi jika diperlukan. Anda dapat melanjutkan dengan Google, mengganti bahasa dari menu atas, atau membuat akun baru.', authVoiceRegisterGuide: 'Selamat datang di pembuatan akun. Masukkan nama lengkap, pilih nama pengguna, masukkan email, buat kata sandi minimal delapan karakter, lalu konfirmasikan. Anda dapat mendaftar dengan Google, mengganti bahasa dari atas, atau kembali ke halaman masuk.' },
  hi: { messages: 'संदेश', contacts: 'संपर्क', settings: 'सेटिंग्स', profile: 'प्रोफ़ाइल', account: 'खाता', notification: 'सूचनाएं', notifications: 'सूचनाएं', darkMode: 'डार्क मोड', language: 'भाषा', editProfile: 'प्रोफ़ाइल संपादित करें', uploadPhoto: 'फोटो अपलोड करें', saveChanges: 'परिवर्तन सहेजें', signOut: 'साइन आउट', appearance: 'दिखावट', connected: 'कनेक्टेड', offline: 'ऑफ़लाइन', search: 'खोजें', chooseLanguage: 'भाषा चुनें', online: 'अभी ऑनलाइन', noFriends: 'अभी कोई मित्र नहीं', authWelcome: 'फिर से स्वागत है', authLoginSubtitle: 'अपनी बातचीत जारी रखने के लिए साइन इन करें।', authCreate: 'अपना खाता बनाएं', authRegisterSubtitle: 'XYTEEE से जुड़ें और अपने लोगों से संपर्क करें।', authFullName: 'पूरा नाम', authUsername: 'यूज़रनेम', authEmail: 'ईमेल पता', authPassword: 'पासवर्ड', authPasswordMinimum: 'पासवर्ड, कम से कम 8 अक्षर', authConfirmPassword: 'पासवर्ड की पुष्टि करें', authShowPassword: 'पासवर्ड दिखाएं', authHidePassword: 'पासवर्ड छिपाएं', authForgotPassword: 'पासवर्ड भूल गए?', authContinue: 'जारी रखें', authCreateAccount: 'खाता बनाएं', authOr: 'या', authContinueGoogle: 'Google के साथ जारी रखें', authSignupGoogle: 'Google से साइन अप करें', authNoAccount: 'खाता नहीं है?', authHaveAccount: 'पहले से खाता है?', authSignup: 'साइन अप', authSignin: 'साइन इन', authPasswordsMismatch: 'पासवर्ड मेल नहीं खाते', authUnableSignin: 'साइन इन नहीं हो सका', authUnableCreate: 'खाता नहीं बन सका', authRecoveryUnavailable: 'पासवर्ड रिकवरी अभी कॉन्फ़िगर नहीं है।', authGoogleUnavailable: 'Google प्रमाणीकरण कॉन्फ़िगरेशन के लिए तैयार है, लेकिन अभी सक्षम नहीं है।', authVoiceOn: 'वॉइस सहायता चालू', authVoiceOff: 'वॉइस सहायता बंद', authVoiceStart: 'वॉइस सहायता चालू करें', authVoiceStop: 'वॉइस सहायता बंद करें', authVoiceLoginGuide: 'साइन इन में आपका स्वागत है। अपना ईमेल पता और पासवर्ड दर्ज करें। आवश्यकता हो तो पासवर्ड भूल गए विकल्प का उपयोग करें। आप Google से जारी रख सकते हैं, ऊपर के मेनू से भाषा बदल सकते हैं, या नया खाता बना सकते हैं।', authVoiceRegisterGuide: 'खाता बनाने में आपका स्वागत है। अपना पूरा नाम दर्ज करें, यूज़रनेम चुनें, ईमेल डालें, कम से कम आठ अक्षरों का पासवर्ड बनाकर उसकी पुष्टि करें। आप Google से साइन अप कर सकते हैं, ऊपर से भाषा बदल सकते हैं, या साइन इन पर लौट सकते हैं।' },
  ar: { messages: 'الرسائل', contacts: 'جهات الاتصال', settings: 'الإعدادات', profile: 'الملف الشخصي', account: 'الحساب', notification: 'الإشعارات', notifications: 'الإشعارات', darkMode: 'الوضع الداكن', language: 'اللغة', editProfile: 'تعديل الملف الشخصي', uploadPhoto: 'رفع صورة', saveChanges: 'حفظ التغييرات', signOut: 'تسجيل الخروج', appearance: 'المظهر', connected: 'متصل', offline: 'غير متصل', search: 'بحث', chooseLanguage: 'اختر اللغة', online: 'متصل الآن', noFriends: 'لا يوجد أصدقاء بعد', authWelcome: 'مرحبًا بعودتك', authLoginSubtitle: 'سجّل الدخول لمتابعة محادثاتك.', authCreate: 'أنشئ حسابك', authRegisterSubtitle: 'انضم إلى XYTEEE وابدأ التواصل مع أصدقائك.', authFullName: 'الاسم الكامل', authUsername: 'اسم المستخدم', authEmail: 'البريد الإلكتروني', authPassword: 'كلمة المرور', authPasswordMinimum: 'كلمة المرور، 8 أحرف على الأقل', authConfirmPassword: 'تأكيد كلمة المرور', authShowPassword: 'إظهار كلمة المرور', authHidePassword: 'إخفاء كلمة المرور', authForgotPassword: 'هل نسيت كلمة المرور؟', authContinue: 'متابعة', authCreateAccount: 'إنشاء حساب', authOr: 'أو', authContinueGoogle: 'المتابعة باستخدام Google', authSignupGoogle: 'التسجيل باستخدام Google', authNoAccount: 'ليس لديك حساب؟', authHaveAccount: 'لديك حساب بالفعل؟', authSignup: 'إنشاء حساب', authSignin: 'تسجيل الدخول', authPasswordsMismatch: 'كلمتا المرور غير متطابقتين', authUnableSignin: 'تعذر تسجيل الدخول', authUnableCreate: 'تعذر إنشاء الحساب', authRecoveryUnavailable: 'استعادة كلمة المرور غير مهيأة بعد.', authGoogleUnavailable: 'مصادقة Google جاهزة للإعداد ولكنها غير مفعلة بعد.', authVoiceOn: 'المساعدة الصوتية مفعلة', authVoiceOff: 'المساعدة الصوتية متوقفة', authVoiceStart: 'تشغيل المساعدة الصوتية', authVoiceStop: 'إيقاف المساعدة الصوتية', authVoiceLoginGuide: 'مرحبًا بك في تسجيل الدخول. أدخل بريدك الإلكتروني ثم كلمة المرور. استخدم خيار نسيت كلمة المرور عند الحاجة. يمكنك المتابعة باستخدام Google أو تغيير اللغة من القائمة العلوية أو إنشاء حساب جديد.', authVoiceRegisterGuide: 'مرحبًا بك في إنشاء الحساب. أدخل اسمك الكامل واختر اسم مستخدم وأدخل بريدك الإلكتروني. أنشئ كلمة مرور من ثمانية أحرف على الأقل ثم أكدها. يمكنك التسجيل باستخدام Google أو تغيير اللغة من الأعلى أو العودة إلى تسجيل الدخول.' },
  es: { messages: 'Mensajes', contacts: 'Contactos', settings: 'Ajustes', profile: 'Perfil', account: 'CUENTA', notification: 'Notificación', notifications: 'Notificaciones', darkMode: 'Modo oscuro', language: 'Idioma', editProfile: 'Editar perfil', uploadPhoto: 'Subir foto', saveChanges: 'Guardar cambios', signOut: 'Cerrar sesión', appearance: 'Apariencia', connected: 'Conectado', offline: 'Desconectado', search: 'Buscar', chooseLanguage: 'Elegir idioma', online: 'En línea ahora', noFriends: 'Aún no hay amigos', authWelcome: 'Te damos la bienvenida', authLoginSubtitle: 'Inicia sesión para continuar tus conversaciones.', authCreate: 'Crea tu cuenta', authRegisterSubtitle: 'Únete a XYTEEE y empieza a conectar con tu gente.', authFullName: 'Nombre completo', authUsername: 'Nombre de usuario', authEmail: 'Correo electrónico', authPassword: 'Contraseña', authPasswordMinimum: 'Contraseña, al menos 8 caracteres', authConfirmPassword: 'Confirmar contraseña', authShowPassword: 'Mostrar contraseña', authHidePassword: 'Ocultar contraseña', authForgotPassword: '¿Olvidaste tu contraseña?', authContinue: 'Continuar', authCreateAccount: 'Crear cuenta', authOr: 'o', authContinueGoogle: 'Continuar con Google', authSignupGoogle: 'Registrarse con Google', authNoAccount: '¿No tienes una cuenta?', authHaveAccount: '¿Ya tienes una cuenta?', authSignup: 'Regístrate', authSignin: 'Inicia sesión', authPasswordsMismatch: 'Las contraseñas no coinciden', authUnableSignin: 'No se pudo iniciar sesión', authUnableCreate: 'No se pudo crear la cuenta', authRecoveryUnavailable: 'La recuperación de contraseña aún no está configurada.', authGoogleUnavailable: 'La autenticación con Google está lista para configurarse, pero aún no está habilitada.', authVoiceOn: 'Ayuda por voz activada', authVoiceOff: 'Ayuda por voz desactivada', authVoiceStart: 'Activar ayuda por voz', authVoiceStop: 'Desactivar ayuda por voz', authVoiceLoginGuide: 'Te damos la bienvenida al inicio de sesión. Introduce tu correo electrónico y después tu contraseña. Usa la opción Olvidaste tu contraseña si lo necesitas. Puedes continuar con Google, cambiar el idioma desde el menú superior o crear una cuenta nueva.', authVoiceRegisterGuide: 'Te damos la bienvenida al registro. Introduce tu nombre completo, elige un nombre de usuario, añade tu correo y crea una contraseña de al menos ocho caracteres y confírmala. Puedes registrarte con Google, cambiar el idioma desde arriba o volver al inicio de sesión.' },
  pt: { messages: 'Mensagens', contacts: 'Contatos', settings: 'Configurações', profile: 'Perfil', account: 'CONTA', notification: 'Notificação', notifications: 'Notificações', darkMode: 'Modo escuro', language: 'Idioma', editProfile: 'Editar perfil', uploadPhoto: 'Enviar foto', saveChanges: 'Salvar alterações', signOut: 'Sair', appearance: 'Aparência', connected: 'Conectado', offline: 'Offline', search: 'Buscar', chooseLanguage: 'Escolher idioma', online: 'Online agora', noFriends: 'Ainda não há amigos', authWelcome: 'Bem-vindo de volta', authLoginSubtitle: 'Entre para continuar suas conversas.', authCreate: 'Crie sua conta', authRegisterSubtitle: 'Entre no XYTEEE e conecte-se com as suas pessoas.', authFullName: 'Nome completo', authUsername: 'Nome de usuário', authEmail: 'Endereço de e-mail', authPassword: 'Senha', authPasswordMinimum: 'Senha, pelo menos 8 caracteres', authConfirmPassword: 'Confirmar senha', authShowPassword: 'Mostrar senha', authHidePassword: 'Ocultar senha', authForgotPassword: 'Esqueceu a senha?', authContinue: 'Continuar', authCreateAccount: 'Criar conta', authOr: 'ou', authContinueGoogle: 'Continuar com o Google', authSignupGoogle: 'Cadastrar com o Google', authNoAccount: 'Não tem uma conta?', authHaveAccount: 'Já tem uma conta?', authSignup: 'Cadastre-se', authSignin: 'Entrar', authPasswordsMismatch: 'As senhas não coincidem', authUnableSignin: 'Não foi possível entrar', authUnableCreate: 'Não foi possível criar a conta', authRecoveryUnavailable: 'A recuperação de senha ainda não está configurada.', authGoogleUnavailable: 'A autenticação do Google está pronta para configuração, mas ainda não está habilitada.', authVoiceOn: 'Ajuda por voz ativada', authVoiceOff: 'Ajuda por voz desativada', authVoiceStart: 'Ativar ajuda por voz', authVoiceStop: 'Desativar ajuda por voz', authVoiceLoginGuide: 'Bem-vindo ao login. Digite seu e-mail e depois sua senha. Use a opção Esqueceu a senha se precisar. Você pode continuar com o Google, trocar o idioma pelo menu superior ou criar uma nova conta.', authVoiceRegisterGuide: 'Bem-vindo à criação de conta. Digite seu nome completo, escolha um nome de usuário, informe seu e-mail e crie uma senha com pelo menos oito caracteres e confirme. Você pode se cadastrar com o Google, trocar o idioma acima ou voltar ao login.' },
};

interface I18nValue { language: LanguageCode; setLanguage: (language: LanguageCode) => void; isRTL: boolean; t: (key: string) => string; }
const I18nContext = createContext<I18nValue | null>(null);

export function I18nProvider({ children }: PropsWithChildren) {
  const [language, setLanguageState] = useState<LanguageCode>('en');
  useEffect(() => { void SecureStore.getItemAsync(LANGUAGE_KEY).then((saved) => { if (languages.some((item) => item.code === saved)) setLanguageState(saved as LanguageCode); }); }, []);
  const setLanguage = (next: LanguageCode) => { setLanguageState(next); void SecureStore.setItemAsync(LANGUAGE_KEY, next); };
  const isRTL = rtlLanguages.has(language);
  useEffect(() => { I18nManager.allowRTL(isRTL); I18nManager.forceRTL(isRTL); }, [isRTL]);
  const value = useMemo(() => ({ language, setLanguage, isRTL, t: (key: string) => translations[language][key] ?? translations.en[key] ?? key }), [language, isRTL]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() {
  const value = useContext(I18nContext);
  if (!value) throw new Error('useI18n must be used inside I18nProvider');
  return value;
}
